name: WarpSystem
author: AirTriX
version: 2.0.6
description: WarpSystem
main: de.codingair.warpsystem.WarpSystem
softdepend: [Multiverse-Core]

commands:
  warp:
    usuage: /Warp
    description: Warp-System-CMD
  warps:
    usuage: /Warps
    description: Warp-System-CMD
  warpsystem:
    usuage: /WarpSystem
    description: Warp-System-CMD
    aliases: [ws]
  portal:
    usuage: /Portal
    description: Setup portals
