name: WarpSystem
author: CodingAir
version: 3.0.1
description: WarpSystem
main: de.codingair.warpsystem.spigot.base.WarpSystem
softdepend: [Multiverse-Core, Vault, Essentials]
api-version: 1.13

commands:
  warp:
    usuage: /Warp
    description: A Warp-System-CMD
  warps:
    usuage: /Warps
    description: A Warp-System-CMD
  warpsystem:
    usuage: /WarpSystem
    description: A Warp-System-CMD
    aliases: [ws]
  portal:
    usuage: /Portal
    description: A Warp-System-CMD
    aliases: [portals]
  globalwarps:
    ususage: /GlobalWarps
    description: A Warp-System-CMD
    aliases: [gws]
  globalwarp:
    ususage: /GlobalWarp
    description: A Warp-System-CMD
    aliases: [gw]
  nativeportals:
    usuage: /NativePortals
    description: A Warp-System-CMD
    aliases: [nativeportal, np, nps]
