name: WarpSystem
author: AirTriX
version: 1.2.0
description: WarpSystem
main: de.codingair.warpsystem.WarpSystem

commands:
  warp:
    usuage: /Warp
    description: Warp-System-CMD
    aliases: [warps]