name: WarpSystem
author: AirTriX
version: 2.0.0
description: WarpSystem
main: de.codingair.warpsystem.WarpSystem
softdepend: [Multiverse-Core]

commands:
  warp:
    usuage: /Warp
    description: Warp-System-CMD
    aliases: [warps]