name: WarpSystem
author: CodingAir
version: 2.1.0
description: WarpSystem
main: de.codingair.warpsystem.spigot.WarpSystem
softdepend: [Multiverse-Core]
api-version: 1.13

commands:
  warp:
    usuage: /Warp
    description: A Warp-System-CMD
  warps:
    usuage: /Warps
    description: A Warp-System-CMD
  warpsystem:
    usuage: /WarpSystem
    description: A Warp-System-CMD
    aliases: [ws]
  portal:
    usuage: /Portal
    description: A Warp-System-CMD
    aliases: [portals]
  globalwarps:
    ususage: /GlobalWarps
    description: A Warp-System-CMD
    aliases: [gw, globalwarp]